### ISSUE TITLE
`Supports Multiple R/W` errors for booleans/coils

### ISSUE THREAD

**Issue by CanuckMarc** [NubeIO/nubeio-rubix-app-modbus-py#29]
@Shiny380 
As discussed yesterday regarding CBA Rundle Mall, we found that there is still an issue with the `Supports Multiple R/W` functionality.  It was writing the wrong value to register 107 (Compressor_Stage_1_Lockout) while `Supports Mulitple R/W` is ON (in < 1 min) and not while it's OFF (left overnight).  

The modbus service was updated to 1.1.0 for these tests.

**Comment by Shiny380** [comment]
app hadn't correctly updated from the platform
